config/routes.rb
 Rails.application.routes.draw do
  get 'contact/new'

   resources :topics, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  resources :comments
  devise_for :users, path: '', path_names:{ sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show, :index] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to:  'contacts#new'
  get 'tech-news', to: 'pages#tech_news'
  get 'portfolio', to: 'portfolios#index', as: 'portfolio_index'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  extend FriendlyId
 friendly_id :title, use: :slugged
 
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda{|attrs| attrs['name'].blank?}

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: "angular")
  end

  def self.by_position
    order ('position ASC')
  end
  scope :ruby_on_rails, -> {where(subtitle: "Ruby on Rails")}

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout 'portfolio'
   access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
  def index
    @portfolio_items = Portfolio.by_position
    @page_title = "Geoff Humphreys - Portfolio"
  end

  def sort
      params[:order].each do |key, value|
        Portfolio.find(value[:id]).update(position: value[:position])
      end

       head :ok
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolio_index_path, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    # @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.friendly.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolio_index_path, notice: 'The record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.friendly.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.friendly.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_index_path, notice: 'Item was successfully destroyed.' }
    end
  end

private

def set_portfolio
  @portfolio_item = Portfolio.friendly.find(params[:id])
end

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :Live_Site,
                                      :git_url,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                     )
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
  "http://placehold.it/#{height}x#{width}"
end

def portfolio_img img, type
  if img.model.main_image? || img.model.thumb_image?
    img
  elsif type == 'thumb'
    image_generator(height: '350', width: '200')
  elsif type == 'main'
    image_generator(height: '600', width: '400')
  end
end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
<% end %>
<div class="row">
  <div class="col-md-6">

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= form.label :Live_Site %>
      <%= form.text_field :Live_Site, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= form.label :git_url %>
      <%= form.text_field :git_url, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= form.label :main_image %>
      <%= form.file_field :main_image %>
    </div>

    <div class="form-group">
      <%= form.label :thumb_image %>
      <%= form.file_field :thumb_image %>
    </div>
  </div>

  <div class="col-md-6">

    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: 'form-control', rows: 13 %>
    </div>

  </div>
</div>

<hr />

<div class="col-md-12">
  <h2>Technologies Used</h2>
  <div>
    <%= form.fields_for :technologies do |technology_form| %>
      <%= render 'technology_fields', f: technology_form %>
    <% end %>
    <div>
      <%= link_to_add_association 'Add Technology', form, :technologies %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
  </div>
</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-6 col-sm-12">
  <div class="card box-shadow" data-id="<%= portfolio_item.id %>">
    <div class="hovereffect">
      <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %>
      <div class="overlay">
        <h2><%= portfolio_item.title %></h2>
        <br />
        <p class="card-text text-center">
          <%= portfolio_item.subtitle %>
        </p>
        <p class="card-text"><%= markdown portfolio_item.body %></p>
      </div>
    </div>
    <div class="pink">
      <div class="row justify-content-center align-items-center">
        <div class="col-6 text-center">
          <figure>
              <%= link_to image_tag("live-site.png"), "#{portfolio_item.Live_Site}", class: "port-icon", :target => "_blank" %>
            <figcaption class="hive-icon-text">
              <%= link_to "finished project", "#{portfolio_item.Live_Site}", :target => "_blank" %>
            </figcaption>
          </figure>
        </div>
        <div class="col-6 text-center">
          <figure>
              <%= link_to image_tag("honey-comb.png"), "#{portfolio_item.git_url}", class: "port-icon", :target => "_blank" %>
            <figcaption class="hive-icon-text">
              <%= link_to "code on github", "#{portfolio_item.git_url}", :target => "_blank" %>
            </figcaption>
          </figure>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Items</h1>

<%= link_to "Create new item", new_portfolio_path %>

<% @angular_portfolio_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
    <%= link_to 'Delete portfolio item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>

  <% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album portfolio-outline">
  <div id="section2" class="container">
    <%= source_helper("alert alert-warning") %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new portfolio item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">


    <div class="col-lg-4 split-lev text-side pink">
      <h1 class="show-port-title text-uppercase"><%= @portfolio_item.title %></h1>

      <hr>

      <em class="show-port-subtitle"><%= @portfolio_item.subtitle %></em>

      <p class="show-port-body"><%= markdown @portfolio_item.body %></p>

      <hr>

      <h3 class="show-tech-title">Technologies Used:</h3>

      <% @portfolio_item.technologies.each do |t| %>
      <p class="show-tech-name"><%= t.name %></p>
      <% end %>



      <div class="row justify-content-around">

        <div class="col-6 text-center">
          <figure>
            <div class="breaker-icon">
              <%= link_to image_tag("live-site.png"), "https://www.linkedin.com/in/geoff-humphreys", :target => "_blank" %>
            </div>
            <figcaption class="hive-icon-text">
              finished product
            </figcaption>
            </figure>
          </div>

          <div class="col-6 text-center">
            <figure>
              <div class="breaker-icon">
                <%= link_to image_tag("honey-comb.png"), "https://www.linkedin.com/in/geoff-humphreys", :target => "_blank" %>
              </div>
              <figcaption class="hive-icon-text">
                code on github
              </figcaption>
            </figure>
            </div>

          </div>


    <% if logged_in?(:site_admin) %>
      <div>
        <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: "btn btn-warning" %>
        <br />
        <br />
        <%= link_to "Delete Item", @portfolio_item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
      <% end %>
    </div>
    <div class="screenshot-side split-lev col-lg-7 col-xs-12 pink">
      <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
    </div>
  </div>
</div>