config/routes.rb
 Rails.application.routes.draw do
  get 'contact/new'

   resources :topics, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  resources :comments
  devise_for :users, path: '', path_names:{ sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show, :index] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to:  'contacts#new'
  get 'tech-news', to: 'pages#tech_news'
  get 'portfolio', to: 'portfolios#index', as: 'portfolio_index'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="footer">  
  <div class="container">
    <div class="row justify-content-center">
      <span class="text-center"><%= copyright_generator %></span>
    </div>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
  <div class="container-fluid application-nav">
    <nav class="navbar nav-masthead app-nav">
    <h3 class="navbar-brand">Geoff Humphreys</h3>
      <%= nav_helper 'nav-link', 'span' %>
      <!-- <%= login_helper 'nav-link' %> -->
    </nav>
  </div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to "Topics", topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container-fluid">
    <%= link_to "Geoff Humphreys", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
   <h4>Topics</h4>
   <% @side_bar_topics.each do |topic| %>
     <p><%= link_to topic.title, topic_path(topic) %></p>
   <% end %>
 </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/paradegoat"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolio_index_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer>
<div class="container">
  <p class="float-right port-footer">
    <a href="#">Back to top</a>
  </p>
  <p class="port-footer">
  <%= copyright_generator %>
  </p>
</div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<div class="portfolio-masthead">
  <section class="jumbotron container-fluid">
    <div class="row mast-row align-items-center">
      <div class="col-12 align-self-center">
        <!-- <h1 class="jumbotron-heading text-center">welcome to my honey house</h1> -->
      </div>
    </div>
    <div class="row mast-row">
      <p class="col-lg-4 offset-lg-8 col-md-6 offset-md-8 col-sm-4 offset-6 align-self-center">
        <%= link_to 'Resume', about_me_path, class: 'btn btn-lg btn-secondary mast-button' %>
      </p>
    </div>
    <div class="row mast-row justify-content-center">
      <p class="col-lg-4 col-md-5 col-sm-10 align-self-center text-center fade-in-text">Developer / Beekeeper / Nice Person </p>
    </div>
  </section>
</div>
<div class="breaker">
  <div class="container">
    <div class="row justify-content-around">
      <figure>
        <div class="breaker-icon">
          <div id="hexagon"><%= link_to image_tag("github.png", width: 60), "http://github.com/paradegoat/", :target => "_blank" %></div>
        </div>
        <figcaption class="hive-icon-text text-center">
          github
        </figcaption>
      </figure>
      <!-- <figure>
        <div class="breaker-icon">
          <div id="hexagon"><%= link_to image_tag("linkedin.png", width: 60), "https://www.linkedin.com/in/geoff-humphreys", :target => "_blank" %></div>
        </div>
        <figcaption class="hive-icon-text text-center">
          linkedin
        </figcaption>
      </figure> -->
      <figure class="alpha">
        <div class="breaker-icon">
          <div id="hexagon"><%= link_to image_tag("connect.png", width: 60), contact_path %></div>
        </div>
        <figcaption class="hive-icon-text text-center">
          contact
        </figcaption>
      </figure>
      <figure>
        <div class="breaker-icon">
          <div id="hexagon"><%= link_to image_tag("resume.png", width: 60), "Humphreys.Geoff_Resume.pdf", :target => "_blank" %></div>
        </div>

        <figcaption class="hive-icon-text text-center">
          resume
        </figcaption>
      </figure>
      <figure>
        <div class="breaker-icon">
          <div id="hexagon"><%= link_to image_tag("down-arrow.png", width: 60), "#section2" %></div>
        </div>
        <figcaption class="hive-icon-text text-center">
          recent work
        </figcaption>
      </figure>

<!-- These were the previous icons that match the portfolio_item link icons -->
      <!-- <figure>
        <div class="breaker-icon">
        <%= link_to image_tag("github.png"), "http://github.com/paradegoat/", :target => "_blank" %>
        </div>
        <figcaption class="hive-icon-text text-center">
          github
        </figcaption>
      </figure>
      <figure>
        <div class="breaker-icon">
        <%= link_to image_tag("linkedin.png"), "https://www.linkedin.com/in/geoff-humphreys", :target => "_blank" %>
        </div>
        <figcaption class="hive-icon-text text-center">
          linkedin
        </figcaption>
      </figure>
      <figure>
        <div class="breaker-icon">
        <%= link_to image_tag("connect.png"), contact_path %>
        </div>
        <figcaption class="hive-icon-text text-center">
          contact
        </figcaption>
      </figure>
      <figure>
        <div class="breaker-icon">
        <%= link_to image_tag("down-arrow.png"), "#section2" %>
        </div>
        <figcaption class="hive-icon-text text-center">
          recent work
        </figcaption>
      </figure> -->


    </div>
  </div>
</div>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse port-nav-color" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h2 class="nav-inner-title">Thanks for stopping by</h2>
        <p class="nav-inner-body">I am a recent graduate of The Iron Yard in Durham, NC and currently a Freelance Developer that focuses on Ruby/Rails.  If you'd like to get in touch with me you can head over to the contact page or you can just send me a message at : <br /> humphreys.geoff@gmail.com</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4 text-center">
        <h2 class="nav-inner-title">menu</h2>
        <ul class="list-unstyled">
          <%= nav_helper 'nav-inner-body', 'li' %>
          <!-- <li><%= login_helper 'text-white' %></li> -->
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark port-nav-color port-nav box-shadow">
  <div class="container d-flex justify-content-between">
    <%= link_to "Geoff Humphreys", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>